package edu.ntnu.k2g3.idatt1002.Controllers;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.Spinner;
import javafx.scene.shape.Line;

public class Tournament16Controller {
    @FXML
    public Spinner spinnerRoundOf16nr2;
    public Spinner spinnerRoundOf16nr6;
    public Spinner spinnerRoundOf16nr1;
    public Spinner spinnerRoundOf16nr5;
    public Spinner spinnerQuarter1;
    public Spinner spinnerQuarter3;
    public Spinner spinnerRoundOf16nr3;
    public Spinner spinnerRoundOf16nr4;
    public Spinner spinnerRoundOf16nr8;
    public Spinner spinnerRoundOf16nr7;
    public Spinner spinnerQuarter2;
    public Spinner spinnerQuarter4;
    public Spinner winnerBracket1Spinner1;
    public Spinner winnerBracket2Spinner;
    public Spinner spinnerTeam2;
    public Spinner spinnerTeam3;
    public Spinner spinnerTeam4;
    public Spinner spinnerTeam7;
    public Spinner spinnerTeam8;
    public Spinner spinnerTeam5;
    public Spinner spinnerTeam6;
    public Spinner spinnerTeam10;
    public Spinner spinnerTeam9;
    public Spinner spinnerTeam12;
    public Spinner spinnerTeam11;
    public Spinner spinnerTeam14;
    public Spinner spinnerTeam13;
    public Spinner spinnerTeam16;
    public Spinner spinnerTeam15;
    public Spinner spinnerTeam1;
    public Label winnerRound16nr6;
    public Label winnerRound16nr5;
    public Label winnerRound16nr2;
    public Label winnerRound16nr1;
    public Label winnerQuarter1;
    public Label winnerQuarter3;
    public Label winnerFinal;
    public Label winnerDisplay;
    public Label winnerRound16nr4;
    public Label winnerRound16nr3;
    public Label winnerRound16nr8;
    public Label winnerRound16nr7;
    public Label winnerQuarter2;
    public Label winnerQuarter4;
    public Label winnerSem1;
    public Label winnerSemi2;
    public Label team2;
    public Label team1;
    public Label team4;
    public Label team3;
    public Label team8;
    public Label team7;
    public Label team6;
    public Label team5;
    public Label team10;
    public Label team9;
    public Label team12;
    public Label team11;
    public Label team14;
    public Label team13;
    public Label team16;
    public Label team15;
    public Line line1winner1;
    public Line line1winner3;
    public Line line1winner7;
    public Line line1winner6;
    public Line line2winner3;
    public Line line2winner1;
    public Line line2winner7;
    public Line line1winner2;
    public Line finalWinnerLine2;
    public Line line2winner6;
    public Line line1winner4;
    public Line line2winner4;
    public Line line2winner5;
    public Line line1winner5;
    public Line line1winner9;
    public Line line2winner9;
    public Line line1winner10;
    public Line line2winner10;
    public Line line2winner2;
    public Line line1winner8;
    public Line line2winner8;
    public Line line1winner11;
    public Line line2winner11;
    public Line finalWinnerLine1;
    public Button exitTournament;
}
